# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420b21ba7d97faef0ca29d21c1bdda557fdd4f02bfe2a551c1fd58d736a23ed7b7aff33c18d15e1928f491b5c16dd51f321095ec037b8a8359a0735df1fb69e3

test:
  secret_key_base: 83385181a384fc0b5591bdd5bc3c0404a72809e5d50e6ff176dc86111fb58bff97793005697d7fb00d85e52438c4ad6ac09b91e44c6c2214753598b8457acaab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
